"""
Hypernetwork — generates routing weights conditioned on current context.

The hypernetwork is a secondary network that produces the weights for the
primary routing network. The hypernetwork itself can be frozen while its
output (the routing weights) changes every forward pass based on context.

Combined with fast weights, this gives two self-modification mechanisms:
1. Fast weights: Hebbian updates from recent activations (short-term memory)
2. Hypernetwork: Context-conditioned weight generation (adaptive routing)
"""

import torch
import torch.nn as nn
import torch.nn.functional as F


class HyperNetwork(nn.Module):
    """
    Generates routing layer weights conditioned on the current context embedding.

    The hypernetwork takes a context vector (from Chestahedron embedding + conversation
    state) and outputs weight matrices for the routing layers. This allows the router's
    behavior to be entirely context-dependent without requiring gradient-based updates.

    Architecture:
        context -> [MLP encoder] -> [weight chunks] -> reshape to target layer shapes
    """

    def __init__(
        self,
        context_dim: int,
        target_shapes: list[tuple[int, int]],
        hidden_dim: int = 128,
        num_layers: int = 2,
    ):
        """
        Args:
            context_dim: dimension of the conditioning context vector
            target_shapes: list of (out_features, in_features) for each generated weight matrix
            hidden_dim: hidden dimension of the hypernetwork MLP
            num_layers: depth of the hypernetwork
        """
        super().__init__()
        self.target_shapes = target_shapes
        self.total_params = sum(out_f * in_f for out_f, in_f in target_shapes)

        # Build the hypernetwork MLP
        layers: list[nn.Module] = []
        in_dim = context_dim
        for _ in range(num_layers - 1):
            layers.extend([
                nn.Linear(in_dim, hidden_dim),
                nn.LayerNorm(hidden_dim),
                nn.GELU(),
            ])
            in_dim = hidden_dim

        # Final layer outputs all target parameters
        layers.append(nn.Linear(in_dim, self.total_params))
        self.mlp = nn.Sequential(*layers)

        # Per-target scaling (learnable initialization scale)
        self.scales = nn.ParameterList([
            nn.Parameter(torch.ones(1) * 0.01)
            for _ in target_shapes
        ])

    def forward(self, context: torch.Tensor) -> list[torch.Tensor]:
        """
        Generate weight matrices conditioned on context.

        Args:
            context: (batch, context_dim) or (context_dim,) context vector

        Returns:
            list of weight tensors, one per target shape
        """
        if context.dim() == 1:
            context = context.unsqueeze(0)

        # Generate all parameters as a flat vector
        raw_params = self.mlp(context)  # (B, total_params)

        # Split and reshape into target weight matrices
        weights = []
        offset = 0
        for idx, (out_f, in_f) in enumerate(self.target_shapes):
            size = out_f * in_f
            chunk = raw_params[:, offset:offset + size]
            w = chunk.view(-1, out_f, in_f) * self.scales[idx]
            weights.append(w)
            offset += size

        return weights


class HyperLinear(nn.Module):
    """
    A linear layer whose weights are generated by a hypernetwork.
    Combines a static base weight with hypernetwork-generated dynamic weight.

    output = (W_base + W_hyper(context)) @ x + bias
    """

    def __init__(
        self,
        in_features: int,
        out_features: int,
        context_dim: int,
        hyper_hidden: int = 64,
    ):
        super().__init__()
        self.in_features = in_features
        self.out_features = out_features

        # Static base weights (slow, learned via backprop)
        self.base_weight = nn.Parameter(
            torch.randn(out_features, in_features) * (2.0 / in_features) ** 0.5
        )
        self.bias = nn.Parameter(torch.zeros(out_features))

        # Hypernetwork generates dynamic weight delta
        self.hyper = HyperNetwork(
            context_dim=context_dim,
            target_shapes=[(out_features, in_features)],
            hidden_dim=hyper_hidden,
        )

        # Gating: how much to trust hyper-generated weights vs base
        self.gate = nn.Parameter(torch.tensor(0.0))  # sigmoid(0) = 0.5

    def forward(self, x: torch.Tensor, context: torch.Tensor) -> torch.Tensor:
        """
        Forward pass with context-conditioned weights.

        Args:
            x: (batch, in_features) input
            context: (batch, context_dim) or (context_dim,) conditioning context

        Returns:
            (batch, out_features) output
        """
        # Generate dynamic weight delta
        (delta_w,) = self.hyper(context)  # (1, out, in) or (B, out, in)

        # Gate between base and base+delta
        alpha = torch.sigmoid(self.gate)
        effective_weight = self.base_weight + alpha * delta_w.squeeze(0)

        # Apply
        return F.linear(x, effective_weight, self.bias)


class RoutingHyperNetwork(nn.Module):
    """
    Top-level hypernetwork that generates weights for multiple routing layers
    conditioned on the full context (Chestahedron state + conversation embedding).

    This is the "context-conditioned weight generator" from the spec.
    The hypernetwork itself is frozen after initial training, but the weights
    it generates change every forward pass.
    """

    def __init__(
        self,
        context_dim: int,
        routing_dim: int,
        num_routing_layers: int = 3,
        hyper_hidden: int = 128,
    ):
        super().__init__()
        self.routing_dim = routing_dim
        self.num_routing_layers = num_routing_layers

        # One hypernetwork generates all routing layer weights
        target_shapes = [
            (routing_dim, routing_dim)
            for _ in range(num_routing_layers)
        ]
        self.weight_generator = HyperNetwork(
            context_dim=context_dim,
            target_shapes=target_shapes,
            hidden_dim=hyper_hidden,
        )

        # Biases are not generated — they're static
        self.biases = nn.ParameterList([
            nn.Parameter(torch.zeros(routing_dim))
            for _ in range(num_routing_layers)
        ])

        # Layer norms (static)
        self.norms = nn.ModuleList([
            nn.LayerNorm(routing_dim)
            for _ in range(num_routing_layers)
        ])

    def forward(
        self, x: torch.Tensor, context: torch.Tensor
    ) -> torch.Tensor:
        """
        Apply context-conditioned routing layers to input.

        Args:
            x: (batch, routing_dim) input to route
            context: (batch, context_dim) or (context_dim,) conditioning context

        Returns:
            (batch, routing_dim) routed output
        """
        # Generate all routing weights from context
        weights = self.weight_generator(context)

        # Apply each generated layer with residual + norm + GELU
        for i in range(self.num_routing_layers):
            w = weights[i].squeeze(0)  # (routing_dim, routing_dim)
            residual = x
            x = self.norms[i](x)
            x = F.linear(x, w, self.biases[i])
            x = F.gelu(x)
            x = x + residual

        return x
